# Generated by Django 4.2.3 on 2023-07-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=140)),
                ('date_birth', models.DateField(default='2023-01-01')),
                ('spec_attribute_value', models.IntegerField(default=0)),
                ('type_attribute_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=140)),
                ('type_attribute', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=140)),
                ('animal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animaltype')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animals')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.commands')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animals')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie_name', models.CharField(max_length=140)),
                ('specie_attribute', models.CharField(max_length=140)),
                ('animal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animaltype')),
            ],
        ),
        migrations.AddField(
            model_name='animals',
            name='animal_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animalspecies'),
        ),
    ]
