# Generated by Django 4.2.3 on 2023-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='spec_attribute_value',
            field=models.CharField(default='', max_length=140),
        ),
    ]
