# Generated by Django 4.2.3 on 2023-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animals_spec_attribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='date',
            field=models.DateField(default='2023-07-01'),
        ),
    ]
